### ISSUE TITLE
review-sbom-practices-add-to-cicd-sop

### ISSUE THREAD

**Issue by david-thrower** [david-thrower/cerebros-core-algorithm-alpha#92]
Kind of issue: Process Change

Review the SBOM and make sure what we are producing meets requirements. Amend CICD SOP as needed.

Suggested Labels (If you don't know, that's ok): triage/hire-consultant kind/secutity-vulnerability

**Comment by riteshnoronha** [comment]
we have created an open-source tool to help you do just this.  As simple as `sbomqs share <sbom-file>` output example https://sbombenchmark.dev/user/score?id=eb4903f6-88df-46bd-adb1-e5ea85cdc88f

https://github.com/interlynk-io/sbomqs

**Comment by david-thrower** [comment]
@riteshnoronha , Thanks for the awesome and practical recommendation. I will prioritize this.

**Comment by riteshnoronha** [comment]
Awesome. Would love any feedback.

**Comment by david-thrower** [comment]
One possibility is:

In .github/workflows/automerge.yaml, append:

```yaml

# Add a pipeline step

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml
        
 
 # Configure trivy.yaml

```
